source 'https://rubygems.org'

gem 'gli'
gem 'bitcoin-client', :github => 'holytransaction/bitcoin-client'
gem 'rspec'
gem 'cucumber'
gem 'awesome_print'
gem 'rake'
gem 'mocha'
gem 'mysql2'
gem 'activerecord'
gem 'standalone_migrations'
gem 'daemons'
gem 'airbrake'
